export { IconLinkedin } from './icon-linkedin'

export { IconArrow } from './icon-arrow'
export { IconCross } from './icon-cross'
export { IconError } from './icon-error'
export { IconHome } from './icon-home'
export { IconInfo } from './icon-info'
export { IconLabel } from './icon-label'
export { IconLetter } from './icon-letter'
export { IconLogout } from './icon-logout'
export { IconMonitor } from './icon-monitor'
export { IconNotebook } from './icon-notebook'
export { IconProfile } from './icon-profile'
export { IconTasks } from './icon-tasks'
export { IconDesing } from './icon-design'
